#!/usr/bin/perl

##############################################################################
#
#  Copyright (C) 2010 Robert Longstaff (rob@longstaff.us)
#  
#      This program is free software; you can redistribute it and/or modify
#      it under the terms of the GNU General Public License as published by
#      the Free Software Foundation; either version 2 of the License, or
#      (at your option) any later version.
#  
#      This program is distributed in the hope that it will be useful,
#      but WITHOUT ANY WARRANTY; without even the implied warranty of
#      MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#      GNU General Public License for more details.
#  
#      You should have received a copy of the GNU General Public License along
#      with this program; if not, write to the Free Software Foundation, Inc.,
#      51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
#
##############################################################################

use warnings;
use strict;

my @req = (qw(
    FindBin::libs
    Readonly
    Log::Log4perl
    Object::Trampoline
    Config::General
    Proc::Reliable
));

my @rec = (qw(
	Crypt::CBC
	Crypt::OpenSSL::AES
));

sub test_pkg {
	my ($pkg) = @_;
	
	print "Testing $pkg...";
	eval "use $pkg;";
	if ($@) {
		print "Missing\n";
		return;
	}
	print "Found\n";
	return 1;
}

my $ok = 1;
foreach my $i (@req) {
	$ok = 0
		unless (test_pkg($i));
}

die "Required packages missing\n"
	unless $ok;

foreach my $i (@rec) {
	$ok = 0
		unless (test_pkg($i));
}

die "Recommended packages missing\n"
	unless $ok;

warn "Object::Trampoline 1.26 is recommended for error reporting\n"
	unless ($Object::Trampoline::VERSION > 1.25);

exit 0;

